name: rideshare
description: "A Flutter app for road trip riders to connect and share experiences."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0   # use latest version
  firebase_auth: ^5.2.0   # since youâ€™re using auth
  http: ^1.2.2            # for PostgreSQL API calls
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.1
  socket_io_client: ^2.0.3+1
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

