version: "3.9"

services:
  db:
    image: postgres:15
    container_name: rideshare-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 820958
      POSTGRES_DB: rideshare_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rideshare-redis
    ports:
      - "6379:6379"          # optional, only needed if you want to connect from host
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build: .
    container_name: backend-server-1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rideshare_db
      DB_USER: postgres
      DB_PASSWORD: 820958

      # Redis for your Python code
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: ""     # set if you secure Redis
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  db_data:
  redis_data:
